version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"

  server:
    image: jetbrains/teamcity-server
    restart: always
    ports:
      - "8111:8111"
    volumes:
      - server-data:/data/teamcity_server/datadir
      - server-logs:/opt/teamcity/logs
    extra_hosts:
      cs-nuc-04: "192.168.198.210"
    depends_on:
      - db

  agent:
    build: ./teamcity-agent
    restart: always
    environment:
      - SERVER_URL=http://server:8111
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
    extra_hosts:
      cs-nuc-04: "192.168.198.210"
    deploy:
      replicas: 3

volumes:
  server-data:
  server-logs:
  pgdata:

